In [2]:
import tensorflow as tf

In [3]:
'''tensors are accessed differently compared to lists
if list = [[1,2,3],[4,5,6]]'''

'tensors are accessed differently compared to lists\nif list = [[1,2,3],[4,5,6]]'

In [4]:
tf.constant(7)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
x = tf.constant(7)
x.ndim #for scalar, number of dimensions = 0

0

In [6]:
y = tf.constant([1,2])
y.ndim #for tensor, number of dimensions = 1 here(number of rows)

1

In [7]:
z = tf.constant([[1,2],[3,4]])
z.ndim #for tensor, number of dimensions = 2 here(number of rows)

2

In [8]:
#tensor dimensions is always number of rows

In [9]:
z #has datatype of int32 => 32 bit integer

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
#but 32 bit int datype when upcasted or downcasted truncates bits => better typecast to float32

In [11]:
tf.cast(z, dtype = tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [12]:
y = tf.Variable(7)

In [13]:
y.assign(10) #we can't change y to y = 10

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=10>

In [14]:
#AttributeError, as the variable itself isn't available

In [15]:
a = tf.constant([[1,2,3,],[4,5,6],[7,8,9]])
a


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [16]:
tf.cast(a, dtype = tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [17]:
a.ndim

2

In [18]:
a.shape

TensorShape([3, 3])

In [19]:
a.ndim #indicates number of directions we can move in !!!

2

In [20]:
a[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [21]:
a[0][0] #empty shape

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [22]:
z = tf.random.Generator.from_seed(10)
random_tensor = z.normal(shape=(2,2))

In [23]:
random_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.29604465, -0.21134205],
       [ 0.01063002,  1.5165398 ]], dtype=float32)>

In [24]:
tf.random.shuffle(random_tensor,seed = 82) #shuffling won't occur due to z being generated from Generator() function

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.29604465, -0.21134205],
       [ 0.01063002,  1.5165398 ]], dtype=float32)>

In [25]:
tf.zeros(1) #dimensions = 1 & tf.zeros() is useful for masking as it creates a zero tensor

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [26]:
tf.zeros((30,30)) #dimensions = 30 x 30

<tf.Tensor: shape=(30, 30), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [27]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [28]:
z = tf.ones((30,30))
tf.cast(z, dtype = tf.int64) #of type int64

<tf.Tensor: shape=(30, 30), dtype=int64, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1,

In [29]:
z.numpy() #to access only the array object such that tensor attributes are removed

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1

In [30]:
z.ndim #can move only in 2 directions

2

In [31]:
tf.expand_dims(tf.zeros((15,15)), axis = 1) #expands along columns

<tf.Tensor: shape=(15, 1, 15), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0.

In [32]:
tf.expand_dims(tf.zeros((15,15)), axis = 0) #expands along rows

<tf.Tensor: shape=(1, 15, 15), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 

In [33]:
tf.expand_dims(tf.zeros((15,15)), axis = -1)  #becomes a column tensor

<tf.Tensor: shape=(15, 15, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
 

In [34]:
#axis = some number => along that index dimensions are expanded

In [35]:
a = [1,2,3]
b = [4,5,6]
a + b #array addition is concatenation

[1, 2, 3, 4, 5, 6]

In [36]:
tf.constant([1,2]) + tf.constant([3,4]) #plain addition

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [37]:
tf.constant([1,2]) - tf.constant([3,4]) #plain subtraction

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [38]:
tf.constant([1,2]) * tf.constant([3,4]) #plain multiplication

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 8], dtype=int32)>

In [39]:
tf.constant([1,2]) / tf.constant([3,4]) #plain division

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.33333333, 0.5       ])>

In [40]:
x = tf.constant([1,2,3])
y = = tf.constant([3,4])
x * y #invalid syntax

SyntaxError: invalid syntax (2019693421.py, line 2)

In [ ]:
tf.reshape(y, shape = (3,1)) #error

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 2 values, but the requested shape has 3 [Op:Reshape]

In [ ]:
x @ y #error

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [] vs. [2] [Op:MatMul] name: 

In [ ]:
a = tf.constant([[1,2,3],[4,5,6]])
b = tf.transpose(a) #works as expected
c = tf.reshape(a, shape = (3,2)) # does a pushdown operation such that values are pushed down everytime
b


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
c

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
b == c

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True, False],
       [False, False],
       [False,  True]])>

In [ ]:
tf.tensordot(a,b,axes = 1,name = None) #to find dot product of 2 vectors/tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [ ]:
tf.abs(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>