In [1]:
import tensorflow as tf

In [2]:
tf.constant(7)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
x = tf.constant([1,2])
x.ndim

1

In [4]:
x = tf.constant([[1,2], [3,4]])
x.ndim

2

In [5]:
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
tf.cast(x, dtype=tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [7]:
y = tf.Variable(7)

In [8]:
y.assign(10)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=10>

In [9]:
x = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
x

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [10]:
x.shape

TensorShape([2, 2, 2])

In [11]:
x.ndim

3

In [12]:
x[0][0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
z = tf.random.Generator.from_seed(7)
random_tensor = z.normal(shape=(2,2))

In [14]:
random_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018]], dtype=float32)>

In [15]:
tf.random.set_seed(32)
tf.random.shuffle(random_tensor, seed=82)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018]], dtype=float32)>

In [16]:
tf.zeros((15,15))
tf.expand_dims(tf.zeros((15,15)), axis=-1)

<tf.Tensor: shape=(15, 15, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
 

In [17]:
tf.constant([1,2]) + tf.constant([3,4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [18]:
[1,2] + [3, 4]

[1, 2, 3, 4]

In [19]:
tf.reshape(tf.constant((3,4)), shape=(2,1))

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [4]], dtype=int32)>

In [20]:
x = tf.constant([[1,2,3],[5,6,7]])
tf.transpose(x), tf.reshape(x, (3,2))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 5],
        [2, 6],
        [3, 7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 5],
        [6, 7]], dtype=int32)>)