In [1]:
import tensorflow as tf
from sklearn.datasets import make_moons

In [2]:
X = make_moons()

In [3]:
X

(array([[ 1.59599895e-01,  9.87181783e-01],
        [ 5.09442530e-02,  1.84891782e-01],
        [-3.45365054e-01,  9.38468422e-01],
        [ 1.46253829e+00, -3.86599306e-01],
        [ 6.54634946e-01, -4.38468422e-01],
        [ 1.83808810e+00, -4.55349012e-02],
        [ 9.67294863e-01,  2.53654584e-01],
        [ 1.87131870e+00,  9.28244800e-03],
        [ 1.61911895e-01, -4.55349012e-02],
        [ 9.60230259e-02,  9.95379113e-01],
        [-6.23489802e-01,  7.81831482e-01],
        [ 3.45365054e-01,  9.38468422e-01],
        [ 1.71834935e+00, -1.95682551e-01],
        [ 8.20998618e-03,  3.72122838e-01],
        [ 4.62538290e-01,  8.86599306e-01],
        [-9.00968868e-01,  4.33883739e-01],
        [ 7.30832427e-02,  1.24732995e-01],
        [ 9.03976974e-01, -4.95379113e-01],
        [ 8.01413622e-01,  5.98110530e-01],
        [ 7.15472413e-01, -4.58667853e-01],
        [ 9.67948422e-01, -4.99486216e-01],
        [ 1.51839257e+00, -3.55142763e-01],
        [ 1.98155916e+00,  3.088

In [4]:
y = X[1]

In [5]:
x = X[0]
x

array([[ 1.59599895e-01,  9.87181783e-01],
       [ 5.09442530e-02,  1.84891782e-01],
       [-3.45365054e-01,  9.38468422e-01],
       [ 1.46253829e+00, -3.86599306e-01],
       [ 6.54634946e-01, -4.38468422e-01],
       [ 1.83808810e+00, -4.55349012e-02],
       [ 9.67294863e-01,  2.53654584e-01],
       [ 1.87131870e+00,  9.28244800e-03],
       [ 1.61911895e-01, -4.55349012e-02],
       [ 9.60230259e-02,  9.95379113e-01],
       [-6.23489802e-01,  7.81831482e-01],
       [ 3.45365054e-01,  9.38468422e-01],
       [ 1.71834935e+00, -1.95682551e-01],
       [ 8.20998618e-03,  3.72122838e-01],
       [ 4.62538290e-01,  8.86599306e-01],
       [-9.00968868e-01,  4.33883739e-01],
       [ 7.30832427e-02,  1.24732995e-01],
       [ 9.03976974e-01, -4.95379113e-01],
       [ 8.01413622e-01,  5.98110530e-01],
       [ 7.15472413e-01, -4.58667853e-01],
       [ 9.67948422e-01, -4.99486216e-01],
       [ 1.51839257e+00, -3.55142763e-01],
       [ 1.98155916e+00,  3.08841371e-01],
       [ 5.

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [7]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(4, activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(4, activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(1, activation=tf.keras.activations.sigmoid)
])
model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
history = model.fit(x_train, y_train, epochs=5)

Epoch 1/5
3/3 [==============================] - 4s 16ms/step - loss: 0.6777 - accuracy: 0.6125
Epoch 2/5
3/3 [==============================] - 0s 7ms/step - loss: 0.6766 - accuracy: 0.5125
Epoch 3/5
3/3 [==============================] - 0s 7ms/step - loss: 0.6759 - accuracy: 0.5125
Epoch 4/5
3/3 [==============================] - 0s 7ms/step - loss: 0.6749 - accuracy: 0.5125
Epoch 5/5
3/3 [==============================] - 0s 7ms/step - loss: 0.6739 - accuracy: 0.5125


In [8]:
len(x)

100

In [9]:
# Computer vision

In [10]:
!wget https://storage.googleapis.com/ztm_tf_course/food_vision/pizza_steak.zip

--2024-03-12 12:17:31--  https://storage.googleapis.com/ztm_tf_course/food_vision/pizza_steak.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.201.207, 74.125.69.207, 64.233.181.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.201.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 109540975 (104M) [application/zip]
Saving to: ‘pizza_steak.zip.1’

pizza_steak.zip.1   100%[===================>] 104.47M   177MB/s    in 0.6s    

2024-03-12 12:17:32 (177 MB/s) - ‘pizza_steak.zip.1’ saved [109540975/109540975]



In [11]:
import zipfile
import os
zipref = zipfile.ZipFile("pizza_steak.zip")
zipref.extractall()
zipref.close()

In [12]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
tf.random.set_seed(42)

train_datagen = ImageDataGenerator(rescale=1/255.)
test_datagen = ImageDataGenerator(rescale=1./255)


train_data = train_datagen.flow_from_directory('pizza_steak/train/',
                                   batch_size = 32,
                                  target_size=(224,224),
                                   class_mode='binary',
                                   seed=42)
test_datag = test_datagen.flow_from_directory('pizza_steak/test/',
                                  batch_size=32,
                                  target_size=(224,224),
                                  class_mode='binary',
                                  seed=42)

Found 1500 images belonging to 2 classes.
Found 500 images belonging to 2 classes.


In [13]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    tf.keras.layers.MaxPool2D((2,2), strides=1),
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPool2D((2,2), strides=1),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 222, 222, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 221, 221, 32)      0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 219, 219, 32)      9248      
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 218, 218, 32)      0         
 g2D)                                                            
                                                                 
 flatten (Flatten)           (None, 1520768)           0         
                                                                 
 dense_3 (Dense)             (None, 1)                

In [15]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
history = model.fit(train_data, epochs=5)

Epoch 1/5
47/47 [==============================] - 13s 146ms/step - loss: 1.9213 - accuracy: 0.5767
Epoch 2/5
47/47 [==============================] - 5s 114ms/step - loss: 0.4937 - accuracy: 0.7487
Epoch 3/5
47/47 [==============================] - 5s 108ms/step - loss: 0.3778 - accuracy: 0.8427
Epoch 4/5
47/47 [==============================] - 5s 95ms/step - loss: 0.2032 - accuracy: 0.9280
Epoch 5/5
47/47 [==============================] - 5s 115ms/step - loss: 0.0970 - accuracy: 0.9780


In [17]:
model.predict(test_datag)

16/16 [==============================] - 2s 123ms/step


array([[9.99263704e-01],
       [6.47889674e-01],
       [9.99626756e-01],
       [1.77584857e-01],
       [6.08320981e-02],
       [9.99952435e-01],
       [9.10183907e-01],
       [1.50593549e-01],
       [9.73026454e-01],
       [6.86169684e-01],
       [5.24070580e-03],
       [5.30826569e-01],
       [1.71097398e-01],
       [3.06986682e-02],
       [9.99159813e-01],
       [9.99900579e-01],
       [7.31326938e-01],
       [5.23472689e-02],
       [5.04521906e-01],
       [9.98950183e-01],
       [2.42089465e-01],
       [3.12464595e-01],
       [1.86049044e-01],
       [9.26121473e-01],
       [4.27457562e-05],
       [9.95033503e-01],
       [9.89205837e-01],
       [2.55204812e-02],
       [3.00976560e-02],
       [9.92360055e-01],
       [9.99988675e-01],
       [1.43449679e-01],
       [9.96552348e-01],
       [1.92002871e-03],
       [8.48222077e-02],
       [8.66523087e-01],
       [6.70176566e-01],
       [2.69358665e-01],
       [5.29441424e-02],
       [1.66010845e-03],
