In [ ]:
import tensorflow as tf

In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/food_vision/101_food_classes_10_percent.zip

--2024-03-25 11:00:16--  https://storage.googleapis.com/ztm_tf_course/food_vision/101_food_classes_10_percent.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.12.27, 142.250.65.123, 172.217.15.251, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.12.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1625420029 (1.5G) [application/zip]
Saving to: ‘101_food_classes_10_percent.zip’

101_food_classes_10 100%[===================>]   1.51G   216MB/s    in 7.1s    

2024-03-25 11:00:23 (220 MB/s) - ‘101_food_classes_10_percent.zip’ saved [1625420029/1625420029]



In [ ]:
import zipfile
zip = zipfile.ZipFile("101_food_classes_10_percent.zip")
zip.extractall()
zip.close()

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator()
test_datagen = ImageDataGenerator()

train_data = train_datagen.flow_from_directory('101_food_classes_10_percent/train',
                                               class_mode='categorical',
                                               batch_size=32,
                                               shuffle=True,
                                               target_size=(48, 48))

test_data = test_datagen.flow_from_directory('101_food_classes_10_percent/test',
                                               class_mode='categorical',
                                               batch_size=32,
                                               target_size=(48, 48))

Found 7575 images belonging to 101 classes.
Found 25250 images belonging to 101 classes.


In [ ]:
len(test_data)

790

In [ ]:
base_model = tf.keras.applications.EfficientNetB0(include_top=False)
base_model.trainable=False

inputs = tf.keras.layers.Input(shape=(48, 48, 3))
x = base_model(inputs)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
outputs = tf.keras.layers.Dense(101, activation='softmax')(x)

model = tf.keras.models.Model(inputs, outputs)

model.compile(loss=tf.keras.losses.CategoricalCrossentropy(),
              optimizer='adam',
              metrics=['accuracy'])
history = model.fit(train_data,
                    epochs=5,
                    validation_data=test_data,
                    validation_steps=int(0.2*len(test_data)))

Epoch 1/5
237/237 [==============================] - 58s 213ms/step - loss: 4.4872 - accuracy: 0.0458 - val_loss: 4.2093 - val_accuracy: 0.0882
Epoch 2/5
237/237 [==============================] - 50s 211ms/step - loss: 4.0363 - accuracy: 0.1207 - val_loss: 3.9158 - val_accuracy: 0.1473
Epoch 3/5
237/237 [==============================] - 51s 216ms/step - loss: 3.7603 - accuracy: 0.1622 - val_loss: 3.7965 - val_accuracy: 0.1545
Epoch 4/5
237/237 [==============================] - 51s 214ms/step - loss: 3.5751 - accuracy: 0.1937 - val_loss: 3.6839 - val_accuracy: 0.1659
Epoch 5/5
237/237 [==============================] - 50s 210ms/step - loss: 3.4126 - accuracy: 0.2252 - val_loss: 3.6849 - val_accuracy: 0.1683


In [ ]:
# NLP
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

--2024-03-25 11:41:34--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.12.27, 142.250.65.123, 172.217.15.251, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.12.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.005s  

2024-03-25 11:41:34 (122 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [ ]:
zip = zipfile.ZipFile("nlp_getting_started.zip")
zip.extractall()
zip.close()

In [ ]:
import pandas as pd
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv("test.csv")

In [ ]:
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
train_df.tail()

id keyword location  \
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1

In [ ]:
train_df_shuffled = train_df.sample(frac = 1, random_state=42)
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [ ]:
import random
random_index = random.randint(0, len(train_df) - 1)
for row in train_df_shuffled[["text", 'target']][random_index : random_index + 5].itertuples():
  index, text, target = row
  print(f"Target: {target}; {'real disaster' if target!=0 else 'not a real disaster'}")
  print("Text:",text,end='\n')
  print("--"*20)

Target: 1; real disaster
Text: This is the first year the Forest Service spent more than half its annual budget on fighting fires. #climatechange http://t.co/D62zfZy0Mi
----------------------------------------
Target: 1; real disaster
Text: Imagine a room with walls that are lava lamps.
----------------------------------------
Target: 0; not a real disaster
Text: Imagini noi si 2 clipuri The Hobbit: The Desolation of Smaug -... http://t.co/j6CfwUKofE #cliptv #desolationofsmaug #poze #thehobbit
----------------------------------------
Target: 1; real disaster
Text: 133 N past  the 5 L lane is reopened. All other lanes are closed. All lanes are open on the 133 S. Trash truck fire cleanup. @KNX1070
----------------------------------------
Target: 0; not a real disaster
Text: Check This Deal : http://t.co/uOoYgBb6aZ Sivan Health and Fitness Basalt Lava Hot Stone Massage Kit with 36 Piece‰Û_ http://t.co/JJxcnwBp15
----------------------------------------


In [ ]:
from sklearn.model_selection import train_test_split
train_sentences, val_sentences, train_labels, val_labels = train_test_split(train_df_shuffled['text'].to_numpy(),
                                                                            train_df_shuffled['target'].to_numpy(),
                                                                            test_size=0.2,
                                                                            random_state=42)

In [ ]:
len(train_sentences), len(val_sentences)

(6090, 1523)

In [ ]:
max_vocab_length = 10000
max_length = round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))
max_length

15

In [ ]:
#convert text to numbers
text_vectorizer = tf.keras.layers.TextVectorization(max_tokens = max_vocab_length,
                                                 output_sequence_length=max_length)

In [ ]:
text_vectorizer.adapt(train_sentences)

In [ ]:
random_sentence = random.choice(train_sentences)
print(random_sentence,'\n' ,len(random_sentence))
text_vectorizer([random_sentence])

One of these candidates is going to have a Frank Grimes level meltdown with how voters love Trump no matter what. http://t.co/pBEgOf4740 
 136


<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[  65,    6,  224,    1,    9,   99,    5,   24,    3, 5142,    1,
         809,  470,   14,   62]])>

In [ ]:
words = text_vectorizer.get_vocabulary()
words[:5]

['', '[UNK]', 'the', 'a', 'in']

In [ ]:
embedding = tf.keras.layers.Embedding(input_dim = max_vocab_length,
                                      output_dim=128,
                                      input_length=max_length)

In [ ]:
sample = embedding(text_vectorizer([random_sentence]))

In [ ]:
sample[0][0]

<tf.Tensor: shape=(128,), dtype=float32, numpy=
array([ 0.04298702, -0.0303215 , -0.01404298, -0.04746897,  0.03204519,
        0.04846175, -0.00165724,  0.00681718, -0.00525437,  0.04464719,
        0.02844964,  0.03274952, -0.02076997,  0.01749908, -0.00140672,
       -0.01997927,  0.01939752,  0.01275067,  0.04986319,  0.00437246,
        0.00960157, -0.04717357, -0.01929665, -0.00624973, -0.02178738,
       -0.04210694, -0.01551253, -0.02545673, -0.00957309,  0.03996185,
        0.01672285, -0.04686093, -0.01462749, -0.01906729, -0.01259847,
       -0.02123395,  0.04868268,  0.02822497, -0.02813884, -0.03616887,
       -0.00930171,  0.02573924, -0.02249026, -0.03155365,  0.033905  ,
        0.01071868,  0.03677282, -0.04976645, -0.02055871,  0.01377464,
        0.03037259, -0.01346407, -0.01997466, -0.0385303 , -0.04903189,
       -0.02282757, -0.04627606, -0.00938941, -0.00525556, -0.01408178,
        0.01915473,  0.01741118, -0.03496823,  0.04804916, -0.01819456,
       -0.048257

In [ ]:
inputs1 = tf.keras.layers.Input(shape=(1,), dtype='string')
y = text_vectorizer(inputs1)
y = embedding(y)
y = tf.keras.layers.GlobalAveragePooling1D()(y)
outputs1 = tf.keras.layers.Dense(1, activation='sigmoid')(y)

model1 = tf.keras.Model(inputs1, outputs1)
model1.compile(loss=tf.keras.losses.BinaryCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
model1.summary()

Model: "model_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_14 (InputLayer)       [(None, 1)]               0         
                                                                 
 text_vectorization (TextVe  (None, 15)                0         
 ctorization)                                                    
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_average_pooling1d_5  (None, 128)               0         
  (GlobalAveragePooling1D)                                       
                                                                 
 dense_9 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1280129 (4.88 MB)
Trainable params: 1280129 (

In [ ]:
history = model1.fit(tf.expand_dims(train_sentences, axis=-1), train_labels,
          epochs=5,
          validation_data=(val_sentences, val_labels))

Epoch 1/5
191/191 [==============================] - 3s 14ms/step - loss: 0.1985 - accuracy: 0.9325 - val_loss: 0.4975 - val_accuracy: 0.7873
Epoch 2/5
191/191 [==============================] - 3s 15ms/step - loss: 0.1684 - accuracy: 0.9463 - val_loss: 0.5221 - val_accuracy: 0.7748
Epoch 3/5
191/191 [==============================] - 3s 17ms/step - loss: 0.1444 - accuracy: 0.9524 - val_loss: 0.5443 - val_accuracy: 0.7754
Epoch 4/5
191/191 [==============================] - 3s 14ms/step - loss: 0.1256 - accuracy: 0.9573 - val_loss: 0.5706 - val_accuracy: 0.7781
Epoch 5/5
191/191 [==============================] - 3s 15ms/step - loss: 0.1096 - accuracy: 0.9657 - val_loss: 0.5992 - val_accuracy: 0.7840
